version: '3'
services: 
   redis:
      image: redis:5.0.8-alpine
      ports: 
         - "6379:6379"
      volumes:
         - ./redis.conf:/usr/local/etc/redis/redis.conf
         - ./redis_data:/data
      command: 
         #https://github.com/docker-library/redis/issues/125
         - /usr/local/etc/redis/redis.conf
         - --requirepass ${REDIS_PASSWD} 


